POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Tatyane Gonçalves",
  "email": "tatyanegoncalves@gmail.com",
}

### 
GET http://localhost:3333/invites/taty123

###
GET http://localhost:3333/subscribers/taty123/ranking/clicks


###
GET http://localhost:3333/subscribers/taty123/ranking/count

###
GET http://localhost:3333/subscribers/taty123/ranking/position
